name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      # 👉 Install Gradle CLI langsung
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.2.1

      - name: Decode Keystore
        run: echo "${{ secrets.SIGNING_KEY }}" | base64 -d > $GITHUB_WORKSPACE/keystore.jks

      # 👉 Build pakai gradle CLI, bukan ./gradlew
      - name: Build Release APK
        run: gradle assembleRelease \
          -Pandroid.injected.signing.store.file=$GITHUB_WORKSPACE/keystore.jks \
          -Pandroid.injected.signing.store.password=${{ secrets.SIGNING_KEY_PASSWORD }} \
          -Pandroid.injected.signing.key.alias=${{ secrets.SIGNING_KEY_ALIAS }} \
          -Pandroid.injected.signing.key.password=${{ secrets.SIGNING_KEY_ALIAS_PASSWORD }}

      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: app/build/outputs/apk/release/app-release.apk
