name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Setup JDK 17
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # 3. Setup Gradle
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      # 4. Generate gradlew baru (karena wrapper lama sudah dihapus)
      - name: Generate Gradle Wrapper
        run: |
          gradle wrapper --gradle-version 8.2.1
          chmod +x gradlew

      # 5. Copy keystore dari secret
      - name: Prepare Keystore
        run: echo "${{ secrets.SIGNING_KEYSTORE_BASE64 }}" | base64 -d > $GITHUB_WORKSPACE/keystore.jks

      # 6. Build APK release
      - name: Build Release APK
        run: |
          ./gradlew :app:assembleRelease \
            -Pandroid.injected.signing.store.file=$GITHUB_WORKSPACE/keystore.jks \
            -Pandroid.injected.signing.store.password=${{ secrets.SIGNING_STORE_PASSWORD }} \
            -Pandroid.injected.signing.key.alias=${{ secrets.SIGNING_KEY_ALIAS }} \
            -Pandroid.injected.signing.key.password=${{ secrets.SIGNING_KEY_PASSWORD }}

      # 7. Upload hasil build (APK)
      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: app/build/outputs/apk/release/*.apk
