name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout source code
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Setup JDK 17 (AGP 8 butuh minimal Java 17)
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # 3. Setup Gradle cache & CLI
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      # 5. Decode keystore dari secret
      - name: Prepare Keystore
        run: echo "${{ secrets.SIGNING_KEYSTORE_BASE64 }}" | base64 -d > $GITHUB_WORKSPACE/keystore.jks

      # 6. Build APK Release
      - name: Build Release APK
        run: |
          ./gradlew :app:assembleRelease --warning-mode all \
            -Pandroid.injected.signing.store.file=$GITHUB_WORKSPACE/keystore.jks \
            -Pandroid.injected.signing.store.password=${{ secrets.SIGNING_STORE_PASSWORD }} \
            -Pandroid.injected.signing.key.alias=${{ secrets.SIGNING_KEY_ALIAS }} \
            -Pandroid.injected.signing.key.password=${{ secrets.SIGNING_KEY_PASSWORD }}

      # 7. Upload hasil APK
      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: app/build/outputs/apk/release/*.apk
